
# Usa una imagen oficial de PHP con Apache
FROM php:7.4-apache

# Instala extensiones necesarias de PHP
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Copia los archivos de tu proyecto al directorio raíz del servidor
COPY . /var/www/html/

# Configura los permisos
RUN chown -R www-data:www-data /var/www/html

# Exposición del puerto 80 para el servidor Apache
EXPOSE 80

# Configuración adicional para Apache
RUN a2enmod rewrite
